export { default as Navbar } from "./navbar.jsx";
export { default as Section1 } from "./section1.jsx";
export { default as Section2 } from "./section2.jsx";
export { default as Section3 } from "./section3.jsx";
export { default as Section4 } from "./section4.jsx";
export { default as Section5 } from "./section5.jsx";
export { default as Section6 } from "./section6.jsx";
export { default as Section7 } from "./section7.jsx";
export { default as TickerBanner } from "./ticker-banner.jsx";
